export default {
    INTERNAL_SERVER_ERROR_CODE: 500,
    INTERNAL_SERVER_ERROR_MESSAGE: 'Internal Server Error',
    ERROR_CODE: 412,
    ERROR_USER_EXITS: "User Already Exists.",
    BAD_REQUEST_CODE: 400,
    NOT_FOUND_CODE: 404,
    NOT_FOUND_MESSAGE: "Not Found",
    UNAUTHORIZE_CODE: 401,
    UNAUTHORIZE_MESSAGE: "Unthorized Can't Access",
    ERROR: "Something Went Wrong",
    ERROR_NOT_USER: "User Not Found.",
    ERROR_WRONG_PASSWORD: "Please Check Password.",
    SUCCESS_CODE: 200,
    SUCCESS: "Success",
    TOKEN_NOT_PROVIDE: "User Token Not Provided.",
    TOKEN_UNAUTHORIZED: "Token Was Unauthorized.",
    USER_NEW_POST: "New Post Created.",
    USER_UPDATE_POST: "Your Post Has Been Updated.",
    USER_DELETE_POST: "Your Post Has Been Deleted.",
    USER_POST_NOT_FOUND: "Post Not Found",
    GET_USER_POST: "Get Post Success",
    POST_NOT_CHANGE: "User Can Not Edit This Post"
};